# Countdown Message
msgs:
  - "&c%days%&6 day(s) left before the server takes a 2 month break, next server popup &c%month% 1st&6."
  - "&6Worlds will &c&nnever&r&6 be &odeleted&r&6 or &ore-generated&r&6!"
